FROM coqorg/coq:8.15.2-ocaml-4.12-flambda
ENV OPAMYES true
ENV VST_NEEDED 2.9
RUN opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam install -j `nproc` \
         menhir.20220210 \
         coq-quickchick \
         coq-vst.$VST_NEEDED
