FROM coqorg/coq:8.12-ocaml-4.11-flambda
ENV OPAMYES true
ENV VST_NEEDED 2.8
RUN opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam install -j `nproc` \
         menhir.20210419 \
         coq-quickchick \
         coq-vst.$VST_NEEDED
