FROM coqorg/coq:8.16.1
ENV OPAMYES true
ENV VST_NEEDED 2.11.1
RUN \
    sudo apt update \
 && sudo apt install wget \
 && wget https://github.com/QuickChick/QuickChick/archive/refs/tags/v.2.0+beta.zip \
 && unzip v.2.0+beta.zip \
 && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam install -j `nproc` \
         ocamlbuild \
         menhir.20220210 \
         coq-mathcomp-ssreflect \
         coq-vst.$VST_NEEDED \
#         coq-quickchick \
 && (cd QuickChick-v.2.0-beta; make; make install)
