FROM coqorg/coq:8.16.1
ENV OPAMYES true
ENV VST_NEEDED 2.11.1
RUN \
    sudo apt update \
 && sudo apt install wget \
 && wget https://github.com/QuickChick/QuickChick/releases/tag/v.2.0%2Bbeta.16 \
 && unzip v.2.0+beta.16.zip \
 && opam install -j `nproc` \
         ocamlbuild \
         coq-ext-lib \
         coq-simple-io \
         menhir.20220210 \
         coq-mathcomp-ssreflect \
         coq-vst.$VST_NEEDED \
         coq-quickchick \
 && (cd QuickChick-v.2.0-beta; make; make install) \
 && rm -rf QuickChick-v.2.0-beta


# BCP 2023: This is probably not needed at all -- delete
# && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
