FROM coqorg/coq:8.15
ENV OPAMYES true
ENV VST_NEEDED 2.11.1
RUN \
    sudo apt-get update \
 && sudo apt-get install wget \
 && wget https://github.com/QuickChick/QuickChick/archive/refs/tags/v.2.0+beta.zip \
 && unzip v.2.0+beta.zip \
 && opam install -j `nproc` \
         menhir.20220210 \
         ocamlbuild \
         coq-mathcomp-ssreflect \
         coq-ext-lib \
         coq-simple-io \
         coq-vst.$VST_NEEDED \
 && (cd QuickChick-v.2.0-beta; make; make install) \
 && rm -rf QuickChick-v.2.0-beta 


# BCP 2023: This is probably not needed at all -- delete
# && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
