FROM coqorg/coq:8.13-ocaml-4.11-flambda
ENV OPAMYES true
RUN opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam update \
 && opam install -j `nproc` \
         coq-quickchick \
         menhir.20210310 \
         coq-vst-32
