FROM coqorg/coq:8.12-ocaml-4.09-flambda
ENV OPAMYES true
RUN opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam update \
 && opam install \
         coq-quickchick \
         coq-compcert.3.7+8.12~coq_platform \
         coq-vst
