FROM coqorg/coq:dev
ENV OPAMYES true
ENV VST_NEEDED 2.11
RUN \
    sudo apt-get update \
 && sudo apt-get install wget \
 && wget https://github.com/QuickChick/QuickChick/archive/refs/tags/v.2.0+beta.zip \
 && unzip v.2.0+beta.zip \
# && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam install -j `nproc` \
         menhir.20220210 \
#         coq-quickchick \
#         coq-vst.$VST_NEEDED \
 && (cd QuickChick-v.2.0-beta; make; make install) \
 && rm -rf QuickChick-v.2.0-beta \
 && sudo apt-get remove wget
