FROM coqorg/coq:8.15.2-ocaml-4.14.0-flambda
ENV OPAMYES true
ENV VST_NEEDED 2.9
RUN \
    sudo apt update \
 && sudo apt install wget \
 && wget https://github.com/QuickChick/QuickChick/archive/refs/tags/v.2.0+beta.zip \
 && unzip v.2.0+beta.zip \
 && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
 && opam install -j `nproc` \
         menhir.20220210 \
         coq-quickchick \
         coq-vst.$VST_NEEDED \
 && (cd QuickChick-v.2.0-beta; make; make install)
