FROM coqorg/coq:dev
ENV OPAMYES true
ENV VST_NEEDED 2.11
RUN \
# BCP 3/23: QuickChick is not working with dev version of Coq!
#   (once it does, 
#    sudo apt-get update \
# && sudo apt-get install wget \
# && wget https://github.com/QuickChick/QuickChick/archive/refs/tags/v.2.0+beta.zip \
 && unzip v.2.0+beta.zip \
 && opam install -j `nproc` \
         ocamlbuild \
         coq-ext-lib \
         coq-simple-io \
         menhir.20220210 \
         coq-vst.$VST_NEEDED \
# && (cd QuickChick-v.2.0-beta; make; make install) \
# && rm -rf QuickChick-v.2.0-beta 

# BCP 2023: This is probably not needed at all -- delete
# && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
