FROM coqorg/coq:dev
ENV OPAMYES true
RUN opam install -j `nproc` \
         ocamlbuild \
         coq-ext-lib \
         coq-simple-io \
         menhir.20220210 \
         coq-quickchick

# BCP 2023: This is probably not needed at all -- delete
# && opam repo add coq-extra-dev https://coq.inria.fr/opam/extra-dev \
